### ISSUE TITLE
[Bug]: Quests are no longer accessable

### ISSUE THREAD

**Issue by Clone11b** [ClaudiusMinimus/CreateForgeSkyBlock#3]
### Pack name

Create on a potato sky edition

### Minecraft Version

1.19.2

### Forge Version

V. 43.2.0

### Modpack Version

1.19.2

### Operating system

Windiws 10

### Minecraft Launcher

Curseforge

### Bug description

After the latest update quests can not be viewed or access in anyway.

### Steps to reproduce

N/a

### Relevant Logs or Crash Report

N/a

### Other Useful Information/Screenshots

N/a

**Comment by ClaudiusMinimus** [comment]
It is likely related to a bug we found in the DefaultSettings mod. See the[ issue report](https://github.com/Jomcraft-Network/DefaultSettings/issues/12)

Try opening your file manager and copying all the files from 
`/minecraft/config/defaultsettings/Default`
to
`/minecraft/config` as shown below. _You might want to back up your files first._
Please let me know if this fixes your quests (and likely other missing configs). If so, I will try to get a fix out today.
![image](https://user-images.githubusercontent.com/17887664/215275165-af39bdb9-32d0-44bd-8a6f-cefea1bbad73.png)

**Comment by Clone11b** [comment]
This worked. Thanks! The only thing i changed was i only copied the ftbquests folder to the config folder.

**Comment by ClaudiusMinimus** [comment]
You might want to copy the rest too. There are some important settings the pack requires. Once you do that, then tweak your settings as needed.
